# Generated by Django 4.2.16 on 2025-05-10 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeslot',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='photo_url',
            field=models.CharField(max_length=300),
        ),
    ]
