# Generated by Django 4.2.16 on 2025-05-10 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_timeslot_date_alter_doctor_photo_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='fcm_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='fcm_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
